### ISSUE TITLE
Job Analysis

### ISSUE THREAD

**Issue by alex-carruth** [fall2021-csc510-group40/WolfJobs#1]
In phase 3, wolf Job will provide the functionality of analysing various aspects of a job. Job Analysis based on various parameters using graphical representation will help in making prediction on which jobs are more preferred and for which jobs applicants have more inclination. Hiring managers can then decide what rewards and salary to be given to the applicants of that job. Even applicants will get to know, which job is being preferred among other applicants.

**Comment by g-fringer** [comment]
Had some issues with the pull request, so this was done manually and added to master.
