### ISSUE TITLE
Chatbot Integration

### ISSUE THREAD

**Issue by alex-carruth** [fall2021-csc510-group40/WolfJobs#3]
Our platform Wolf Job will also provide the functionality of Chatbot integrated with our website so that user can easily interact with the bot and get to know about various features of our web application and have a nice interactive experience.

**Comment by MrKaStep** [comment]
Do we need a bot that explains how to use a website? I could dig the idea of having a bot that acts as a simple way to search jobs on the platform, but definitely not as a manual to the website itself

**Comment by alex-carruth** [comment]
We decided this was an unnecessary addition to the website.
