### ISSUE TITLE
Fix missing assets

### ISSUE THREAD

**Issue by MrKaStep** [fall2021-csc510-group40/WolfJobs#8]
At the very least, there's missing gear icon for the settings button

**Comment by Dangpham0305** [comment]
assign me. I think i can help you

**Comment by MrKaStep** [comment]
@Dangpham0305 Thanks for volunteering, but I think we'll do it ourselves. Most likely we will transition from using external assets to having our own, so that part will be reworked anyways

**Comment by b4443** [comment]
Fixed.
