### ISSUE TITLE
Fix manager registration

### ISSUE THREAD

**Issue by MrKaStep** [fall2021-csc510-group40/WolfJobs#9]
Currently, the role choice field doesn't have a default value, and just pressing "Signup" isn't working. Choosing the "Applicant" and then going back to "Manager" seems to fix it, but that's not the way to do in

**Comment by g-fringer** [comment]
Added an extra option to the signup dropdown to give a default value for the select box. Also added logic to ensure that errors don't arise trying to create an account with a role that is with that default value.

**Comment by MrKaStep** [comment]
Merged manually, see PR #10
